"""模块说明：把 IR 生成为规范化 C 代码，便于检查和构建。"""

from __future__ import annotations

from .typing import BackendMeta
from ..ir import IRFunction, IRInstruction, IRProgram


def emit_portable_c(program: IRProgram, meta: BackendMeta) -> str:
    lines = [
        "/* Generated by C-Core-Compiler first-generation backend.",
        " * The output is normalized C, not native assembly.",
        " * This keeps the first generation readable and cross-platform. */",
        "",
        "#include <stdint.h>",
        "",
    ]

    for global_var in program.globals:
        if global_var.initializer is None:
            lines.append(f"int {global_var.name} = 0;")
        else:
            lines.append(f"int {global_var.name} = {global_var.initializer};")
    if program.globals:
        lines.append("")

    function_signatures = {function.name: function for function in program.functions}
    for function in program.functions:
        params = ", ".join(f"int {name}" for name in function.params) or "void"
        lines.append(f"int {function.name}({params});")
    if program.functions:
        lines.append("")

    for function in program.functions:
        lines.extend(_emit_function(function, meta))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _emit_function(function: IRFunction, meta: BackendMeta) -> list[str]:
    params = ", ".join(f"int {name}" for name in function.params) or "void"
    lines = [
        f"/* backend target: {meta.target_name} */",
        f"int {function.name}({params}) {{",
    ]

    decls = function.locals + function.temporaries
    if decls:
        # 统一在函数开头声明局部变量和临时变量，
        # 让后面的控制流代码只负责赋值和跳转。
        lines.append("    int " + ", ".join(dict.fromkeys(decls)) + ";")
    for instruction in function.instructions:
        lines.extend(_emit_instruction(instruction))
    lines.append("}")
    return lines


def _emit_instruction(instruction: IRInstruction) -> list[str]:
    op = instruction.opcode
    args = instruction.args

    if op == "label":
        return [f"{args[0]}: ;"]
    if op == "const":
        return [f"    {args[0]} = {args[1]};"]
    if op == "copy":
        return [f"    {args[0]} = {args[1]};"]
    if op == "load":
        return [f"    {args[0]} = {args[1]};"]
    if op == "store":
        return [f"    {args[0]} = {args[1]};"]
    if op == "unary":
        return [f"    {args[0]} = ({args[1]}{args[2]});"]
    if op == "binary":
        return [f"    {args[0]} = ({args[2]} {args[1]} {args[3]});"]
    if op == "jump":
        return [f"    goto {args[0]};"]
    if op == "cjump":
        return [f"    if ({args[0]}) goto {args[1]}; else goto {args[2]};"]
    if op == "call":
        callee = args[1]
        call_args = ", ".join(args[2:])
        return [f"    {args[0]} = {callee}({call_args});"]
    if op == "return":
        return [f"    return {args[0]};"]
    raise AssertionError(f"unsupported IR opcode: {op}")
