"""模块说明：把 IR 生成为规范化 C 代码，便于检查和构建。"""

from __future__ import annotations

from .. import ast_nodes as ast
from .typing import BackendMeta
from ..ir import IRFunction, IRInstruction, IRProgram


def emit_portable_c(program: IRProgram, meta: BackendMeta) -> str:
    if program.requires_ast_backend and isinstance(program.source_program, ast.Program):
        return _emit_portable_c_from_ast(program.source_program, meta)

    lines = [
        "/* Generated by C-Core-Compiler first-generation backend.",
        " * The output is normalized C, not native assembly.",
        " * This keeps the first generation readable and cross-platform. */",
        "",
        "#include <stdint.h>",
        "",
    ]

    for global_var in program.globals:
        if global_var.initializer is None:
            lines.append(f"int {global_var.name} = 0;")
        else:
            lines.append(f"int {global_var.name} = {global_var.initializer};")
    if program.globals:
        lines.append("")

    function_signatures = {function.name: function for function in program.functions}
    for function in program.functions:
        params = ", ".join(f"int {name}" for name in function.params) or "void"
        lines.append(f"int {function.name}({params});")
    if program.functions:
        lines.append("")

    for function in program.functions:
        lines.extend(_emit_function(function, meta))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _emit_function(function: IRFunction, meta: BackendMeta) -> list[str]:
    params = ", ".join(f"int {name}" for name in function.params) or "void"
    lines = [
        f"/* backend target: {meta.target_name} */",
        f"int {function.name}({params}) {{",
    ]

    decls = function.locals + function.temporaries
    if decls:
        # 统一在函数开头声明局部变量和临时变量，
        # 让后面的控制流代码只负责赋值和跳转。
        lines.append("    int " + ", ".join(dict.fromkeys(decls)) + ";")
    for instruction in function.instructions:
        lines.extend(_emit_instruction(instruction))
    lines.append("}")
    return lines


def _emit_instruction(instruction: IRInstruction) -> list[str]:
    op = instruction.opcode
    args = instruction.args

    if op == "label":
        return [f"{args[0]}: ;"]
    if op == "const":
        return [f"    {args[0]} = {args[1]};"]
    if op == "copy":
        return [f"    {args[0]} = {args[1]};"]
    if op == "load":
        return [f"    {args[0]} = {args[1]};"]
    if op == "store":
        return [f"    {args[0]} = {args[1]};"]
    if op == "unary":
        return [f"    {args[0]} = ({args[1]}{args[2]});"]
    if op == "binary":
        return [f"    {args[0]} = ({args[2]} {args[1]} {args[3]});"]
    if op == "jump":
        return [f"    goto {args[0]};"]
    if op == "cjump":
        return [f"    if ({args[0]}) goto {args[1]}; else goto {args[2]};"]
    if op == "call":
        callee = args[1]
        call_args = ", ".join(args[2:])
        return [f"    {args[0]} = {callee}({call_args});"]
    if op == "return":
        return [f"    return {args[0]};"]
    raise AssertionError(f"unsupported IR opcode: {op}")


def _emit_portable_c_from_ast(program: ast.Program, meta: BackendMeta) -> str:
    lines = [
        "/* Generated by C-Core-Compiler AST backend.",
        " * This path is used for advanced language features such as char,",
        " * strings, arrays and pointers. */",
        "",
        "#include <stdint.h>",
        "",
    ]

    for decl in program.declarations:
        if isinstance(decl, ast.GlobalVarDecl):
            line = _render_declaration(decl.ctype, decl.name)
            if decl.initializer is not None:
                line += f" = {_render_expr(decl.initializer)}"
            lines.append(line + ";")
    if program.declarations:
        lines.append("")

    for decl in program.declarations:
        if isinstance(decl, ast.FunctionDecl):
            params = ", ".join(_render_declaration(param.ctype, param.name) for param in decl.params) or "void"
            lines.append(f"{_render_type_prefix(decl.return_type)} {decl.name}({params});")
    if any(isinstance(decl, ast.FunctionDecl) for decl in program.declarations):
        lines.append("")

    for decl in program.declarations:
        if isinstance(decl, ast.FunctionDecl):
            params = ", ".join(_render_declaration(param.ctype, param.name) for param in decl.params) or "void"
            lines.append(f"/* backend target: {meta.target_name} */")
            lines.append(f"{_render_type_prefix(decl.return_type)} {decl.name}({params}) {{")
            lines.extend(_render_block_items(decl.body.items, 1))
            lines.append("}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_block_items(items: list[ast.Statement], indent: int) -> list[str]:
    lines: list[str] = []
    for item in items:
        lines.extend(_render_stmt(item, indent))
    return lines


def _render_stmt(stmt: ast.Statement, indent: int) -> list[str]:
    pad = "    " * indent
    if isinstance(stmt, ast.Block):
        lines = [pad + "{"]
        lines.extend(_render_block_items(stmt.items, indent + 1))
        lines.append(pad + "}")
        return lines
    if isinstance(stmt, ast.VarDeclStmt):
        line = pad + _render_declaration(stmt.ctype, stmt.name)
        if stmt.initializer is not None:
            line += f" = {_render_expr(stmt.initializer)}"
        return [line + ";"]
    if isinstance(stmt, ast.ExpressionStmt):
        if stmt.expression is None:
            return [pad + ";"]
        return [pad + _render_expr(stmt.expression) + ";"]
    if isinstance(stmt, ast.IfStmt):
        lines = [pad + f"if ({_render_expr(stmt.condition)})"]
        lines.extend(_render_stmt(stmt.then_branch, indent))
        if stmt.else_branch is not None:
            lines.append(pad + "else")
            lines.extend(_render_stmt(stmt.else_branch, indent))
        return lines
    if isinstance(stmt, ast.WhileStmt):
        lines = [pad + f"while ({_render_expr(stmt.condition)})"]
        lines.extend(_render_stmt(stmt.body, indent))
        return lines
    if isinstance(stmt, ast.ForStmt):
        init = _render_for_init(stmt.init)
        cond = _render_expr(stmt.condition) if stmt.condition is not None else ""
        update = _render_expr(stmt.update) if stmt.update is not None else ""
        lines = [pad + f"for ({init}; {cond}; {update})"]
        lines.extend(_render_stmt(stmt.body, indent))
        return lines
    if isinstance(stmt, ast.ReturnStmt):
        if stmt.value is None:
            return [pad + "return;"]
        return [pad + f"return {_render_expr(stmt.value)};"]
    raise AssertionError(f"unsupported AST statement: {type(stmt)!r}")


def _render_for_init(stmt: ast.Statement | None) -> str:
    if stmt is None:
        return ""
    if isinstance(stmt, ast.VarDeclStmt):
        text = _render_declaration(stmt.ctype, stmt.name)
        if stmt.initializer is not None:
            text += f" = {_render_expr(stmt.initializer)}"
        return text
    if isinstance(stmt, ast.ExpressionStmt):
        return "" if stmt.expression is None else _render_expr(stmt.expression)
    raise AssertionError(f"unsupported for-init statement: {type(stmt)!r}")


def _render_expr(expr: ast.Expression) -> str:
    if isinstance(expr, ast.IntLiteral):
        return str(expr.value)
    if isinstance(expr, ast.CharLiteral):
        return expr.value
    if isinstance(expr, ast.StringLiteral):
        return expr.value
    if isinstance(expr, ast.Name):
        return expr.identifier
    if isinstance(expr, ast.UnaryExpr):
        return f"({expr.operator}{_render_expr(expr.operand)})"
    if isinstance(expr, ast.BinaryExpr):
        return f"({_render_expr(expr.left)} {expr.operator} {_render_expr(expr.right)})"
    if isinstance(expr, ast.CallExpr):
        return f"{expr.callee}({', '.join(_render_expr(arg) for arg in expr.args)})"
    if isinstance(expr, ast.AssignExpr):
        return f"({_render_expr(expr.target)} = {_render_expr(expr.value)})"
    if isinstance(expr, ast.IndexExpr):
        return f"{_render_expr(expr.target)}[{_render_expr(expr.index)}]"
    raise AssertionError(f"unsupported AST expression: {type(expr)!r}")


def _render_type_prefix(ctype: ast.CType) -> str:
    return ctype.base + ("*" * ctype.pointer_level)


def _render_declaration(ctype: ast.CType, name: str) -> str:
    base = _render_type_prefix(ast.CType(ctype.base, ctype.pointer_level))
    if ctype.array_size is not None:
        return f"{base} {name}[{ctype.array_size}]"
    return f"{base} {name}"
