"""模块说明：把 IR 或 AST 生成为规范化 C 代码。"""

from __future__ import annotations

from .. import ast_nodes as ast
from .typing import BackendMeta
from ..ir import IRFunction, IRInstruction, IRProgram

_HEADER = (
    "/* Generated by C-Core-Compiler. */\n"
    "\n"
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <string.h>\n"
    "#include <stdint.h>\n"
    "#include <unistd.h>\n"
    "#include <ctype.h>\n"
    "\n"
)

_PRINT_INT_HELPER = (
    "int print_int(int value) {\n"
    '    printf("%d\\n", value);\n'
    "    return value;\n"
    "}\n"
    "\n"
)


def emit_portable_c(program: IRProgram, meta: BackendMeta) -> str:
    if program.requires_ast_backend and isinstance(program.source_program, ast.Program):
        return _emit_from_ast(program.source_program, meta)
    return _emit_from_ir(program, meta)


# ── IR 路径（纯 int，无指针/struct/void 时走这里）──────────────────────────

def _emit_from_ir(program: IRProgram, meta: BackendMeta) -> str:
    lines = [_HEADER, _PRINT_INT_HELPER]

    for gv in program.globals:
        if gv.initializer is None:
            lines.append(f"int {gv.name} = 0;\n")
        else:
            lines.append(f"int {gv.name} = {gv.initializer};\n")
    if program.globals:
        lines.append("\n")

    for fn in program.functions:
        params = ", ".join(f"int {n}" for n in fn.params) or "void"
        lines.append(f"int {fn.name}({params});\n")
    if program.functions:
        lines.append("\n")

    for fn in program.functions:
        lines.extend(_emit_ir_function(fn, meta))
        lines.append("\n")

    return "".join(lines).rstrip() + "\n"


def _emit_ir_function(fn: IRFunction, meta: BackendMeta) -> list[str]:
    params = ", ".join(f"int {n}" for n in fn.params) or "void"
    lines = [
        f"/* backend: {meta.target_name} */\n",
        f"int {fn.name}({params}) {{\n",
    ]
    decls = list(dict.fromkeys(fn.locals + fn.temporaries))
    if decls:
        lines.append("    int " + ", ".join(decls) + ";\n")
    for instr in fn.instructions:
        lines.extend(_emit_ir_instr(instr))
    lines.append("}\n")
    return lines


def _emit_ir_instr(instr: IRInstruction) -> list[str]:
    op, args = instr.opcode, instr.args
    if op == "label":  return [f"{args[0]}: ;\n"]
    if op == "const":  return [f"    {args[0]} = {args[1]};\n"]
    if op == "copy":   return [f"    {args[0]} = {args[1]};\n"]
    if op == "load":   return [f"    {args[0]} = {args[1]};\n"]
    if op == "store":  return [f"    {args[0]} = {args[1]};\n"]
    if op == "unary":  return [f"    {args[0]} = ({args[1]}{args[2]});\n"]
    if op == "binary": return [f"    {args[0]} = ({args[2]} {args[1]} {args[3]});\n"]
    if op == "jump":   return [f"    goto {args[0]};\n"]
    if op == "cjump":  return [f"    if ({args[0]}) goto {args[1]}; else goto {args[2]};\n"]
    if op == "call":
        call_args = ", ".join(args[2:])
        return [f"    {args[0]} = {args[1]}({call_args});\n"]
    if op == "return": return [f"    return {args[0]};\n"]
    raise AssertionError(f"unsupported IR opcode: {op}")


# ── AST 路径（char/string/指针/struct/void 时走这里）───────────────────────

def _emit_from_ast(program: ast.Program, meta: BackendMeta) -> str:
    ast_note = "/* Generated by C-Core-Compiler AST backend. */\n\n"
    lines = [ast_note, _HEADER[_HEADER.index("#"):], _PRINT_INT_HELPER]

    # 1. struct 定义 / typedef
    for decl in program.declarations:
        if isinstance(decl, ast.StructDecl):
            lines.extend(_render_struct_decl(decl))
            lines.append("\n")
        elif isinstance(decl, ast.TypedefDecl):
            lines.append(f"typedef {_render_type(decl.ctype)} {decl.alias};\n\n")

    # 2. 全局变量
    for decl in program.declarations:
        if isinstance(decl, ast.GlobalVarDecl):
            line = _render_decl(decl.ctype, decl.name)
            if decl.initializer is not None:
                line += f" = {_render_expr(decl.initializer)}"
            lines.append(line + ";\n")
    if any(isinstance(d, ast.GlobalVarDecl) for d in program.declarations):
        lines.append("\n")

    # 3. 函数原型（仅前向声明，跳过 extern，因为 #include 已经引入了）
    for decl in program.declarations:
        if isinstance(decl, ast.FuncPrototype):
            if not decl.is_extern:
                lines.append(_render_func_proto(decl) + ";\n")
        elif isinstance(decl, ast.FunctionDecl):
            ret = _render_type(decl.return_type)
            params = _render_params(decl.params)
            lines.append(f"{ret} {decl.name}({params});\n")
    if any(isinstance(d, (ast.FuncPrototype, ast.FunctionDecl)) for d in program.declarations):
        lines.append("\n")

    # 4. 函数体
    for decl in program.declarations:
        if isinstance(decl, ast.FunctionDecl):
            ret = _render_type(decl.return_type)
            params = _render_params(decl.params)
            lines.append(f"/* backend: {meta.target_name} */\n")
            lines.append(f"{ret} {decl.name}({params}) {{\n")
            for stmt in decl.body.items:
                lines.extend(_render_stmt(stmt, 1))
            lines.append("}\n\n")

    return "".join(lines).rstrip() + "\n"


# ── 类型渲染 ────────────────────────────────────────────────────────────────

def _render_type(ctype: ast.CType) -> str:
    if ctype.base == "struct":
        base = f"struct {ctype.struct_name}" if ctype.struct_name else "struct"
    else:
        base = ctype.base
    return base + "*" * ctype.pointer_level


def _render_decl(ctype: ast.CType, name: str) -> str:
    base = _render_type(ast.CType(ctype.base, pointer_level=ctype.pointer_level, struct_name=ctype.struct_name))
    if ctype.array_size is not None:
        dims = f"[{ctype.array_size}]"
        if ctype.array_size2 is not None:
            dims += f"[{ctype.array_size2}]"
        return f"{base} {name}{dims}"
    return f"{base} {name}"


def _render_params(params: list[ast.Parameter]) -> str:
    if not params:
        return "void"
    return ", ".join(_render_decl(p.ctype, p.name) for p in params)


def _render_func_proto(decl: ast.FuncPrototype) -> str:
    prefix = "extern " if decl.is_extern else ""
    ret = _render_type(decl.return_type)
    params = _render_params(decl.params)
    if decl.is_variadic:
        params = (params + ", ...") if decl.params else "..."
    return f"{prefix}{ret} {decl.name}({params})"


def _render_struct_decl(decl: ast.StructDecl) -> list[str]:
    parts: list[str] = []
    if decl.alias:
        parts.append("typedef ")
    if decl.tag:
        parts.append(f"struct {decl.tag}")
    else:
        parts.append("struct")
    if decl.fields is not None:
        parts.append(" {\n")
        for f in decl.fields:
            parts.append(f"    {_render_decl(f.ctype, f.name)};\n")
        parts.append("}")
    if decl.alias:
        parts.append(f" {decl.alias}")
    parts.append(";\n")
    return parts


# ── 语句渲染 ────────────────────────────────────────────────────────────────

def _render_stmt(stmt: ast.Statement, indent: int) -> list[str]:
    pad = "    " * indent

    if isinstance(stmt, ast.Block):
        lines = [pad + "{\n"]
        for item in stmt.items:
            lines.extend(_render_stmt(item, indent + 1))
        lines.append(pad + "}\n")
        return lines

    if isinstance(stmt, ast.VarDeclStmt):
        line = pad + _render_decl(stmt.ctype, stmt.name)
        if stmt.initializer is not None:
            line += f" = {_render_expr(stmt.initializer)}"
        return [line + ";\n"]

    if isinstance(stmt, ast.ExpressionStmt):
        if stmt.expression is None:
            return [pad + ";\n"]
        return [pad + _render_expr(stmt.expression) + ";\n"]

    if isinstance(stmt, ast.IfStmt):
        lines = [pad + f"if ({_render_expr(stmt.condition)})\n"]
        lines.extend(_render_stmt(stmt.then_branch, indent))
        if stmt.else_branch is not None:
            lines.append(pad + "else\n")
            lines.extend(_render_stmt(stmt.else_branch, indent))
        return lines

    if isinstance(stmt, ast.WhileStmt):
        lines = [pad + f"while ({_render_expr(stmt.condition)})\n"]
        lines.extend(_render_stmt(stmt.body, indent))
        return lines

    if isinstance(stmt, ast.ForStmt):
        init_s = _render_for_init(stmt.init)
        cond_s = _render_expr(stmt.condition) if stmt.condition is not None else ""
        upd_s = _render_expr(stmt.update) if stmt.update is not None else ""
        lines = [pad + f"for ({init_s}; {cond_s}; {upd_s})\n"]
        lines.extend(_render_stmt(stmt.body, indent))
        return lines

    if isinstance(stmt, ast.ReturnStmt):
        if stmt.value is None:
            return [pad + "return;\n"]
        return [pad + f"return {_render_expr(stmt.value)};\n"]

    if isinstance(stmt, ast.BreakStmt):
        return [pad + "break;\n"]

    if isinstance(stmt, ast.ContinueStmt):
        return [pad + "continue;\n"]

    raise AssertionError(f"unsupported statement: {type(stmt)!r}")


def _render_for_init(stmt: ast.Statement | None) -> str:
    if stmt is None:
        return ""
    if isinstance(stmt, ast.VarDeclStmt):
        text = _render_decl(stmt.ctype, stmt.name)
        if stmt.initializer is not None:
            text += f" = {_render_expr(stmt.initializer)}"
        return text
    if isinstance(stmt, ast.ExpressionStmt):
        return "" if stmt.expression is None else _render_expr(stmt.expression)
    raise AssertionError(f"unsupported for-init: {type(stmt)!r}")


# ── 表达式渲染 ───────────────────────────────────────────────────────────────

def _render_expr(expr: ast.Expression) -> str:
    if isinstance(expr, ast.IntLiteral):
        return str(expr.value)
    if isinstance(expr, ast.CharLiteral):
        return expr.value
    if isinstance(expr, ast.StringLiteral):
        return expr.value
    if isinstance(expr, ast.Name):
        return expr.identifier
    if isinstance(expr, ast.UnaryExpr):
        return f"({expr.operator}{_render_expr(expr.operand)})"
    if isinstance(expr, ast.BinaryExpr):
        return f"({_render_expr(expr.left)} {expr.operator} {_render_expr(expr.right)})"
    if isinstance(expr, ast.CallExpr):
        args = ", ".join(_render_expr(a) for a in expr.args)
        return f"{expr.callee}({args})"
    if isinstance(expr, ast.AssignExpr):
        return f"({_render_expr(expr.target)} {expr.op} {_render_expr(expr.value)})"
    if isinstance(expr, ast.TernaryExpr):
        return f"({_render_expr(expr.cond)} ? {_render_expr(expr.then_expr)} : {_render_expr(expr.else_expr)})"
    if isinstance(expr, ast.IndexExpr):
        return f"{_render_expr(expr.target)}[{_render_expr(expr.index)}]"
    if isinstance(expr, ast.MemberExpr):
        op = "->" if expr.arrow else "."
        return f"{_render_expr(expr.target)}{op}{expr.member}"
    if isinstance(expr, ast.PostfixIncDecExpr):
        return f"({_render_expr(expr.operand)}{expr.op})"
    if isinstance(expr, ast.CastExpr):
        return f"(({_render_type(expr.ctype)}){_render_expr(expr.operand)})"
    if isinstance(expr, ast.SizeofExpr):
        if expr.ctype is not None:
            return f"sizeof({_render_type(expr.ctype)})"
        return f"sizeof({_render_expr(expr.expr)})"
    raise AssertionError(f"unsupported expression: {type(expr)!r}")
